# Site settings
title: bubchi89.github.io
email: robqliu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My description that will appear in my document head meta (for
  Google search results) and in my feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bubchi89.github.io" # the base hostname & protocol for your site
github_username:  bubchi89

# Build settings
markdown: kramdown

timezone: PST

defaults:
  -
    scope:
      # Can't just use path: "_posts". See https://github.com/jekyll/jekyll/issues/2371
      type: "posts"
    values:
      layout: "post"

